Fixing chrun to set current directory
adamgordonbell/chroot-containers pull request #4
Opened 2023-02-08 20:49 UTC by adamgordonbell

2023-02-08 20:53 UTC, adamgordonbell commented on chrun.go
> +	must(syscall.Chdir(root))
If working dir is left outside the new root it can break things.

2023-02-09 19:34 UTC, davc0n requested changes

2023-02-09 19:34 UTC, davc0n commented on chrun.go
> +	must(syscall.Fchdir(int(oldrootHandle.Fd())))
Why not must(syscall.Chdir(oldrootHandle.Name())) ? Name method returns the full path.

2023-02-09 21:07 UTC, adamgordonbell commented on chrun.go
> +	must(syscall.Fchdir(int(oldrootHandle.Fd())))
I think that wouldn't work because the name will be resolved relative to the current (inside the container) root and so won't exist. 

`must(oldroot.Chdir())` works, but I wanted to call the syscall wrapper directly to show where I'm making calls to the kernel.

2023-02-09 21:30 UTC, merged